# Generated by Django 3.0.2 on 2020-01-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_spreadsheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrant',
            name='exam',
            field=models.CharField(choices=[('JOB', 'JOB'), ('GO', 'GO'), ('TRIAL', 'TRIAL'), ('PA', 'PA')], max_length=10),
        ),
    ]
