# Generated by Django 3.0.2 on 2020-01-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_spreadsheet', '0002_auto_20200112_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrant',
            name='exam',
            field=models.CharField(choices=[('GO', 'GO'), ('PA', 'PA'), ('JOB', 'JOB'), ('TRIAL', 'TRIAL')], max_length=10),
        ),
    ]
