# Generated by Django 3.0.2 on 2020-01-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_spreadsheet', '0003_auto_20200112_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrant',
            name='exam',
            field=models.CharField(choices=[('TRIAL', 'TRIAL'), ('GO', 'GO'), ('PA', 'PA'), ('JOB', 'JOB')], max_length=10),
        ),
    ]
